Capstone: Prize_giving
MPDADDY/capstone_prize-giving_day pull request #1
Opened 2023-07-31 12:42 UTC by MPDADDY

This is a webpage that communicates the on comming prize-giving as well as the venue where is will be held.

2023-07-31 16:45 UTC, nedjwab requested changes
# Changes Required ♻️
### Hi @MPDADDY 
Nice job, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Highlights) Good Points: :
- Good implementation of some of the project requirements  ✔
- GitHub flow was correctly used ✔.

## (Changes Required) Aspects to improve: ♻️
You did great implementing some of the project requirements, but you still have some issues: 
check the comments below 
 👇👇👇

 
## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-07-31 16:45 UTC, nedjwab commented on README.md
> +### Live Demo  - click [TriumphTribute]()
[ ] kindly add the link to your deployed website here, so your readme looks more professional.🤓

2023-07-31 16:45 UTC, nedjwab commented on about.html
> +        <a href="index.html">TriumphTribute</a>
[ ] Kindly change the footer's color on the About page ( desktop version) to black to match the design provided.🤓
your design 👇:
![his](https://github.com/MPDADDY/capstone_prize-giving_day/assets/62156607/29b56a4e-e4f4-47e8-9acc-90d97d99a51b)

Figma design 👇 :
![design](https://github.com/MPDADDY/capstone_prize-giving_day/assets/62156607/5a43826b-1167-4815-8cdd-cfc96adde2f8)

2023-07-31 16:45 UTC, nedjwab commented on about.html
> +        <div class="deskMenu">
[ ] Kindly add some margin so your navbar matches the one in the Figma design🤓
Your design 👇: 
![navhis](https://github.com/MPDADDY/capstone_prize-giving_day/assets/62156607/a124bae8-aa5a-43b5-b382-46aa3cd03f24)

Figma design 👇 : 
![navd](https://github.com/MPDADDY/capstone_prize-giving_day/assets/62156607/3e785639-06f3-4e52-95ea-7a3627bd1f26)

2023-08-01 13:27 UTC, cynthiainga requested changes
Hi @MPDADDY, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

 ## Highlights

- [ ] No linters errors ✔️ 
- [ ] Correct GitHub flow ✔️ 
- [ ] Good design ✔️ 

 ## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇🏾 👇🏾 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-01 13:27 UTC, cynthiainga commented on styles.css
> +
- [ ] Good job implementing the requested changes for About's footer but in the mobile menu now the text is invisible. The background is white and the text is in white also, that is why we can't see the text, the text should be in black color. Kindly fix that 🙏🏾 

<img width="437" alt="Screenshot 2023-08-01 at 15 44 34" src="https://github.com/MPDADDY/capstone_prize-giving_day/assets/74501523/53566ca0-1494-4480-97b5-2884ccbe3173">

2023-08-01 13:27 UTC, cynthiainga commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] The first reviewer forgot to mention it but you should fix the broken MIT link, having broken links in the README is not very professional 🙃 🙃 

<img width="714" alt="Screenshot 2023-08-01 at 16 16 07" src="https://github.com/MPDADDY/capstone_prize-giving_day/assets/74501523/7721bef0-4353-47ec-be5e-e9e17b6cf8ac">

2023-08-01 17:04 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @MPDADDY 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-01 20:04 UTC, merged